### PR TITLE
Export context for hooks support

### PR DESCRIPTION
**Pull request by zalishchuk**
Export `ParallaxContext` for [`useContext`](https://reactjs.org/docs/hooks-reference.html#usecontext) hook support.

### CODE REVIEW

**Comment by zalishchuk** [comment]
Also added a `useController` hook which exposes the `parallaxController` using React hooks.

Usage example:
```jsx
import React, { useLayoutEffect } from 'react';
import { useController } from 'react-scroll-parallax';

const App = () => {
  const { parallaxController } = useController();

  useLayoutEffect(() => {
    const handler = () => parallaxController.update();
    window.addEventListener('load', handler);
    return () => window.removeEventListener('load', handler);
  }, [parallaxController]);

  return (
    <div>
      {'...'}
    </div>
  );
};
```

**Comment by zalishchuk** [comment]
@jscottsmith any thoughts on this?

**Comment by jscottsmith** [comment]
Love it. 

Can you update the README documenting this export. Your usage example would be good to add there too. 

https://github.com/jscottsmith/react-scroll-parallax#parallax-controller-context

**Comment by zalishchuk** [comment]
Updated the README, check it if everything is fine.

**Comment by zalishchuk** [comment]
@jscottsmith ping ✋

**Comment by jscottsmith** [comment]
Looks good, I’ll get it merged and publish a new release tonight.

Thanks for the contribution!

**Comment by jscottsmith** [comment]
@zalishchuk published [2.2.0](https://github.com/jscottsmith/react-scroll-parallax/releases/tag/2.2.0)

**Pull request merged**
